// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WooliesxChallenge.Proxy.Resource.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Incomming request object for passing the candidates details
    /// </summary>
    public partial class DeveloperExerciseApiModelsTrolleyExerciseRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// DeveloperExerciseApiModelsTrolleyExerciseRequest class.
        /// </summary>
        public DeveloperExerciseApiModelsTrolleyExerciseRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// DeveloperExerciseApiModelsTrolleyExerciseRequest class.
        /// </summary>
        /// <param name="token">Unique token used to track candidate
        /// progress.</param>
        /// <param name="url">Url for your api which tests will be run
        /// against.</param>
        public DeveloperExerciseApiModelsTrolleyExerciseRequest(System.Guid? token = default(System.Guid?), string url = default(string))
        {
            Token = token;
            Url = url;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unique token used to track candidate progress.
        /// </summary>
        [JsonProperty(PropertyName = "token")]
        public System.Guid? Token { get; set; }

        /// <summary>
        /// Gets or sets url for your api which tests will be run against.
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

    }
}
