// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WooliesxChallenge.Proxy.Resource.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DeveloperExerciseModelsTrolleySpecial
    {
        /// <summary>
        /// Initializes a new instance of the
        /// DeveloperExerciseModelsTrolleySpecial class.
        /// </summary>
        public DeveloperExerciseModelsTrolleySpecial()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// DeveloperExerciseModelsTrolleySpecial class.
        /// </summary>
        public DeveloperExerciseModelsTrolleySpecial(IList<DeveloperExerciseModelsTrolleyProductQuantity> quantities = default(IList<DeveloperExerciseModelsTrolleyProductQuantity>), double? total = default(double?))
        {
            Quantities = quantities;
            Total = total;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantities")]
        public IList<DeveloperExerciseModelsTrolleyProductQuantity> Quantities { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public double? Total { get; set; }

    }
}
