// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WooliesxChallenge.Proxy.Resource.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DeveloperExerciseModelsSortProduct
    {
        /// <summary>
        /// Initializes a new instance of the
        /// DeveloperExerciseModelsSortProduct class.
        /// </summary>
        public DeveloperExerciseModelsSortProduct()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// DeveloperExerciseModelsSortProduct class.
        /// </summary>
        public DeveloperExerciseModelsSortProduct(string name = default(string), double? price = default(double?), double? quantity = default(double?))
        {
            Name = name;
            Price = price;
            Quantity = quantity;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public double? Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantity")]
        public double? Quantity { get; set; }

    }
}
