// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WooliesxChallenge.Proxy.Resource.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DeveloperExerciseModelsTrolleyProductQuantity
    {
        /// <summary>
        /// Initializes a new instance of the
        /// DeveloperExerciseModelsTrolleyProductQuantity class.
        /// </summary>
        public DeveloperExerciseModelsTrolleyProductQuantity()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// DeveloperExerciseModelsTrolleyProductQuantity class.
        /// </summary>
        public DeveloperExerciseModelsTrolleyProductQuantity(string name = default(string), int? quantity = default(int?))
        {
            Name = name;
            Quantity = quantity;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantity")]
        public int? Quantity { get; set; }

    }
}
