// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WooliesxChallenge.Proxy.Resource
{
    using Microsoft.Rest;
    using Models;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// </summary>
    public partial interface IDevChallengeResourceClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Exercise 1 - Basic response (token and name).
        /// </summary>
        /// <remarks>
        /// This will call your api looking for a resource available at your
        /// base url /user.
        ///
        /// For example, if the url you request is
        /// "http://localhost:5001/api/answers" this will make a GET request to
        /// "http://localhost:5001/api/answers/user"
        ///
        /// The result will be a JSON object in the format {"name": "test",
        /// "token" : "1234-455662-22233333-3333"}
        /// </remarks>
        /// <param name='request'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<DeveloperExerciseServicesExerciseResult>>> ApiExerciseExercise1PostWithHttpMessagesAsync(DeveloperExerciseApiModelsTrolleyExerciseRequest request = default(DeveloperExerciseApiModelsTrolleyExerciseRequest), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Exercise 2 - This will test your sorting endpoint.
        /// </summary>
        /// <remarks>
        /// This will call your api looking for a range of different sorting
        /// options at your base url /sort
        ///
        /// Your Api needs to call the "products" resource to get a list of
        /// available products
        ///
        /// This endpoint will need to accept a query string parameter called
        /// "sortOption" which will take in the following strings
        ///
        /// - "Low" - Low to High Price
        /// - "High" - High to Low Price
        /// - "Ascending" - A - Z sort on the Name
        /// - "Descending" - Z - A sort on the Name
        /// - "Recommended" - this will call the "shopperHistory" resource to
        /// get a list of customers orders and needs to return based on
        /// popularity,
        ///
        /// Your response will be in the same data structure as the "products"
        /// response (only sorted correctly)
        /// </remarks>
        /// <param name='request'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<DeveloperExerciseServicesExerciseResult>>> ApiExerciseExercise2PostWithHttpMessagesAsync(DeveloperExerciseApiModelsTrolleyExerciseRequest request = default(DeveloperExerciseApiModelsTrolleyExerciseRequest), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Exercise 3 - Given products specials and quantities, return the
        /// trolleys total.
        /// </summary>
        /// <remarks>
        /// &lt;br /&gt;This will call your api looking for a resource
        /// available at your base url /trolleyTotal which should return the
        /// lowest possible total based on provided lists of prices, specials
        /// and quantities.
        /// &lt;br /&gt;&lt;br /&gt; Example of the post request can be found
        /// in the /Resources Api below.
        /// </remarks>
        /// <param name='request'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<DeveloperExerciseServicesExerciseResult>>> ApiExerciseExercise3PostWithHttpMessagesAsync(DeveloperExerciseApiModelsTrolleyExerciseRequest request = default(DeveloperExerciseApiModelsTrolleyExerciseRequest), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// This will return all customers buying habits for a range of
        /// products
        /// </summary>
        /// <remarks>
        /// This is not a test - it is a resource for exercise 2
        /// </remarks>
        /// <param name='token'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<DeveloperExerciseModelsSortShopperOrders>>> ApiResourceShopperHistoryGetWithHttpMessagesAsync(System.Guid token, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// This will return all customers buying habits for a range of
        /// products
        /// </summary>
        /// <remarks>
        /// This is not a test - it is a resource for exercise 2
        /// </remarks>
        /// <param name='token'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<DeveloperExerciseModelsSortProduct>>> ApiResourceProductsGetWithHttpMessagesAsync(System.Guid token, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// This will return the lowest total given products, specials and
        /// quantities.
        /// </summary>
        /// <remarks>
        /// This is not a test - it is a (optional) resource for exercise 3
        /// </remarks>
        /// <param name='token'>
        /// </param>
        /// <param name='request'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<int?>> ApiResourceTrolleyCalculatorPostWithHttpMessagesAsync(System.Guid token, DeveloperExerciseModelsTrolleyTrolley request = default(DeveloperExerciseModelsTrolleyTrolley), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

    }
}
